apiVersion: apps/v1     # simple Deployment Yaml file for nginx
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontendapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontendapp
  template:
    metadata:
      labels:
        app: frontendapp
    spec:
      containers:
      - name: appcontainer 
        image: gurudevsingh/my-notes-app:latest

        ports:
        - containerPort: 8000
