apiVersion: v1 # LoadBalancer is a service type that exposes the service externally using a cloud provider’s load balancer
kind: Service
metadata:
  name: my-frontend-service
spec:
  type: LoadBalancer
  clusterIP: 10.0.171.123 # Cluster IP is the IP address assigned to the service
  loadBalancerIP: 123.123.123.123 # LoadBalancer IP is the IP address assigned to the load balancer
  selector:
    app: web
  ports:
  - name: http # Name of the port
    protocol: TCP # Protocol used by the port
    port: 80 # Port in which the service is exposed
    targetPort: 8000 # Port in which the container is listening